stages:
  - install
  - deploy

install:
  stage: install
  image: gradle:jdk8
  script:
    - ./gradlew installDist

deploy:
  stage: deploy
  image:
    name: docker:stable
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - rm -rf .ecs
    - wget -O /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    - chmod +x /usr/local/bin/ecs-cli
