sudo: required

language: java

services:
 - docker

script:
 - ./gradlew installDist
 - docker build --tag=cnuss/greeting-service:travis_$TRAVIS_BUILD_NUMBER .
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.docker.com
 - docker push cnuss/greeting-service:travis_$TRAVIS_BUILD_NUMBER
